[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 64

[rpc_endpoints]
base = "${BASE_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
localBase = "${LOCAL_BASE_RPC_URL}"
flowSepolia = "${FLOW_RPC_URL}"

[etherscan]
base_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
