[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 64
